
DROP SEQUENCE MYNOSEQ;

DROP SEQUENCE GROUPNOSEQ;

DROP TABLE MYBOARD;

CREATE SEQUENCE MYNOSEQ;

CREATE SEQUENCE GROUPNOSEQ;

CREATE TABLE MYBOARD(
	MYNO NUMBER NOT NULL,
	MYNAME VARCHAR2(1000) NOT NULL,
	MYTITLE VARCHAR2(2000) NOT NULL,
	MYCONTENT VARCHAR2(4000) NOT NULL,
	MYDATE DATE NOT NULL,
	CONSTRAINT ANSWER_MYNO_PK PRIMARY KET (MYNO),
);



