DROP SEQUENCE BOARDNOSEQ02;
DROP SEQUENCE GROUPNOSEQ02;
DROP TABLE ANSWERBOARD02;

CREATE SEQUENCE BOARDNOSEQ02;
CREATE SEQUENCE GROUPNOSEQ02;

-- 글번호, 그룹번호, 그룹순서, 제목공백, 삭제여부('Y','N')
-- 제목, 내용, 작성자, 작성일
CREATE TABLE ANSWERBOARD02(
	BOARDNO NUMBER NOT NULL,
	GROUPNO NUMBER NOT NULL,
	GROUPSEQ NUMBER NOT NULL,
	TITLETAB NUMBER NOT NULL,
	DELFLAG VARCHAR2(2) NOT NULL,
	TITLE VARCHAR2(1000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	WRITER VARCHAR2(100) NOT NULL,
	REGDATE DATE NOT NULL,
	-- 제약조건 1 : BOARDNO에 ANSWER_BOARDNO_PK라는 이름으로 PK 걸자
	CONSTRAINT ANSWER_BOARDNO_PK PRIMARY KEY(BOARDNO),
	-- 제약조건 2 : DELFLAG에 ANSWER_DELFLAG_CK라는 이름으로 CHECK 걸자 ('Y','N')
	CONSTRAINT ANSWER_DELFLAG_CK CHECK(DELFLAG IN('Y','N'))
);

-- 1. 글작성
INSERT INTO ANSWERBOARD02
VALUES(BOARDNOSEQ02.NEXTVAL, GROUPNOSEQ02.NEXTVAL, 1, 0, 'N', '답변형재밌다', '정말재밌다.', '반장', SYSDATE);

-- 1번글에 답급
--UPDATE
-- 부모의 그룹번호와 같은 그룹이면서
-- 부모의 그룹순서보다 더 큰 글들의
-- 그룹순서 + 1
UPDATE ANSWERBOARD02
SET GROUPSEQ = GROUPSEQ + 1
WHERE GROUPNO = (SELECT GROUPNO FROM ANSWERBOARD02 WHERE BOARDNO = 1)
AND GROUPSEQ > (SELECT GROUPNO FROM ANSWERBOARD02 WHERE BOARDNO = 1);
--INSERT
INSERT INTO ANSWERBOARD02
VALUES(
	BOARDNOSEQ02.NEXTVAL,
	(SELECT GROUPNO FROM ANSWERBOARD02 WHERE BOARDNO = 1),
	(SELECT GROUPSEQ FROM ANSWERBOARD02 WHERE BOARDNO = 1) + 1,
	(SELECT TITLETAB + 1 FROM ANSWERBOARD02 WHERE BOARDNO = 1),
	'N',
	'RE:답변형재밌다.',
	'진짜 재밌는거 맞아?',
	'강사',
	SYSDATE
);

--1번글 삭제
UPDATE ANSWERBOARD02
SET DELFLAG = 'Y'
WHERE BOARDNO = 1;


SELECT BOARDNO, GROUPNO, GROUPSEQ, TITLETAB, DELFLAG, TITLE, CONTENT, WRITER, REGDATE
FROM ANSWERBOARD02
ORDER BY GROUPNO DESC, GROUPSEQ;