
DROP SEQUENCE MYNOSEQ;

DROP TABLE MYBOARD;

CREATE SEQUENCE MYNOSEQ;

CREATE TABLE MYBOARD(
	MYNO NUMBER PRIMARY KEY,	
	MYNAME VARCHAR2(1000) NOT NULL,
	MYTITLE VARCHAR2(2000) NOT NULL,
	MYCONTENT VARCHAR2(4000) NOT NULL,
	MYDATE DATE NOT NULL,
	VIEWCNT NUMBER NOT NULL
);


INSERT INTO MYBOARD
VALUES(MYNOSEQ.NEXTVAL, '관리자', '스프링 재밌다.', '정말 재밌다.', SYSDATE, 0);


SELECT MYNO, MYNAME, MYTITLE, MYCONTENT, MYDATE, VIEWCNT
FROM MYBOARD
ORDER BY MYNO DESC;

		
------------------------------------------------------------------------

DROP SEQUENCE MYMEMBERSEQ;

DROP TABLE MYMEMBER;

CREATE SEQUENCE MYMEMBERSEQ;

CREATE TABLE MYMEMBER(
	MEMBERNO NUMBER NOT NULL,
	MEMBERID VARCHAR2(1000) NOT NULL,
	MEMBERPW VARCHAR2(1000) NOT NULL,
	MEMBERNAME VARCHAR2(1000) NOT NULL,
	MEMBERADDR VARCHAR2(2000) NOT NULL,
	MEMBERPHONE VARCHAR2(20) NOT NULL,
	MEMBEREMAIL VARCHAR2(100) NOT NULL,
	MEMBERENABLED VARCHAR2(2) NOT NULL,
	MEMBERROLE VARCHAR2(100) NOT NULL,
	CONSTRAINT MYMEMBER_MEMBERNO_PK PRIMARY KEY (MEMBERNO),
	CONSTRAINT MYMEMBER_MEMBERID_UQ UNIQUE(MEMBERID),
	CONSTRAINT MYMEMBER_MEMBERPHONE_UQ UNIQUE(MEMBERPHONE),
	CONSTRAINT MYMEMBER_MEMBEREMAIL_UQ UNIQUE(MEMBEREMAIL),
	CONSTRAINT MYMEMBER_MEMBERENABLED_CHK CHECK(MEMBERENABLED IN ('Y', 'N'))
);

INSERT INTO MYMEMBER
VALUES(MYMEMBERSEQ.NEXTVAL, 'admin', '1234', '관리자', '경기도 수원시', '011-0000-0000', 'hong@admin.com', 'Y', 'ADMIN');


SELECT MEMBERNO, MEMBERID, MEMBERPW, MEMBERNAME, MEMBERADDR, MEMBERPHONE, MEMBEREMAIL, MEMBERENABLED, MEMBERROLE
FROM MYMEMBER
ORDER BY MEMBERNO DESC;